lingvist:
    categorize: [fr]
    exclude: null

memrise:
    categorize: null
    exclude: null 

memrise/common-fr-phrases:
    categorize: null
    exclude: null

memrise/hacking-fr:
    categorize: [at-the-market]
    exclude: null

memrise/minimum-viable-fr:
    categorize: null
    exclude: null

